"""WoHelp web app and JSON API."""
import os

from flask import Flask, jsonify, redirect, render_template, request, session, url_for
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import SQLAlchemyError

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DATABASE_URL = "sqlite:///" + os.path.join(BASE_DIR, "wohelp.db")

SURVEY_COLUMNS = {
    "curso": "TEXT", "turma": "TEXT", "interesse_area_tecnica": "TEXT",
    "motivo_desinteresse": "TEXT", "continuar_estudos": "TEXT",
    "motivo_continuar_estudos": "TEXT", "violencia_curso": "TEXT",
    "motivo_violencia_curso": "TEXT", "violencia_futura": "TEXT",
    "motivo_violencia_futura": "TEXT",
}
CURSOS = ("Eletromecânica", "Metalurgia", "Mecânica", "Petróleo e Gás Natural")
TURMAS = ("1", "2", "3", "4")
PERGUNTAS_VIOLENCIA_OPCIONAIS = {"violencia_curso", "violencia_futura"}
MOTIVOS_VIOLENCIA_OPCIONAIS = {"motivo_violencia_curso", "motivo_violencia_futura"}


def database_url():
    url = os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL)
    if url.startswith("postgres://"):
        url = "postgresql+psycopg://" + url[len("postgres://"):]
    elif url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)
    return url


def create_app(test_config=None):
    app = Flask(__name__)
    app.config.update(
        SECRET_KEY=os.environ.get("WOHELP_SECRET_KEY", "dev-only-change-me"),
        SESSION_COOKIE_HTTPONLY=True,
        SESSION_COOKIE_SAMESITE=os.environ.get("SESSION_COOKIE_SAMESITE", "Lax"),
        SESSION_COOKIE_SECURE=os.environ.get("SESSION_COOKIE_SECURE", "false").lower() == "true",
        MAX_CONTENT_LENGTH=16 * 1024,
    )
    if test_config:
        app.config.update(test_config)

    @app.context_processor
    def form_choices():
        return {"cursos": CURSOS, "turmas": TURMAS}

    engine = create_engine(app.config.get("DATABASE_URL") or database_url(), pool_pre_ping=True)
    app.extensions["wohelp_engine"] = engine

    origins = {o.strip().rstrip("/") for o in os.environ.get("CORS_ORIGINS", "").split(",") if o.strip()}

    def initialize_database():
        id_column = (
            "INTEGER PRIMARY KEY AUTOINCREMENT" if engine.dialect.name == "sqlite"
            else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        )
        with engine.begin() as conn:
            conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS alunos (
                    id {id_column}, nome TEXT NOT NULL, idade INTEGER NOT NULL,
                    aspiracao TEXT, universidade TEXT
                )"""))
            conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS mensagens (
                    id {id_column}, aluno_id INTEGER NOT NULL, mensagem TEXT NOT NULL,
                    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (aluno_id) REFERENCES alunos(id)
                )"""))
            # Migração segura: só adiciona colunas que realmente faltam.
            existentes = {c["name"] for c in inspect(conn).get_columns("alunos")}
            for nome, tipo in SURVEY_COLUMNS.items():
                if nome not in existentes:
                    conn.execute(text(f"ALTER TABLE alunos ADD COLUMN {nome} {tipo}"))

            campos_analise = ["id", "idade", *SURVEY_COLUMNS]
            views = set(inspect(conn).get_view_names())
            if "dados_pesquisa" in views:
                inspector = inspect(conn)
                campos_existentes = {c["name"] for c in inspector.get_columns("dados_pesquisa")}
                definicao = inspector.get_view_definition("dados_pesquisa") or ""
                if campos_existentes != set(campos_analise) or "DISTINCT" not in definicao.upper():
                    conn.execute(text("DROP VIEW dados_pesquisa"))
                    views.remove("dados_pesquisa")
            if "dados_pesquisa" not in views:
                conn.execute(text(
                    f"CREATE VIEW dados_pesquisa AS SELECT DISTINCT {', '.join(campos_analise)} "
                    "FROM alunos WHERE curso IS NOT NULL"
                ))

            # Remove estruturas legadas sem uso somente se estiverem vazias.
            tabelas = set(inspect(conn).get_table_names())
            if "contas" in tabelas and conn.execute(text("SELECT COUNT(*) FROM contas")).scalar_one() == 0:
                conn.execute(text("DROP TABLE contas"))

            tabelas_legadas = [nome for nome in ("respostas_itens", "respostas") if nome in tabelas]
            if tabelas_legadas and all(
                conn.execute(text(f'SELECT COUNT(*) FROM "{nome}"')).scalar_one() == 0
                for nome in tabelas_legadas
            ):
                for nome in tabelas_legadas:
                    conn.execute(text(f'DROP TABLE "{nome}"'))

    with app.app_context():
        initialize_database()

    @app.after_request
    def cors_headers(response):
        origin = request.headers.get("Origin", "").rstrip("/")
        if origin in origins:
            response.headers["Access-Control-Allow-Origin"] = origin
            response.headers["Access-Control-Allow-Credentials"] = "true"
            response.headers["Access-Control-Allow-Headers"] = "Content-Type"
            response.headers["Access-Control-Allow-Methods"] = "GET, POST, PATCH, OPTIONS"
            response.headers["Vary"] = "Origin"
        return response

    @app.get("/health")
    def health():
        try:
            with engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            return jsonify(status="ok")
        except SQLAlchemyError:
            return jsonify(status="unavailable"), 503

    def get_student(student_id):
        if not student_id:
            return None
        with engine.connect() as conn:
            row = conn.execute(
                text("SELECT id, nome, idade, aspiracao, universidade FROM alunos WHERE id = :id"),
                {"id": student_id},
            ).mappings().first()
        return dict(row) if row else None

    def validate_data(data, partial=False, survey=False):
        """Valida nome/idade (+ aspiração/universidade opcionais).
        Com survey=True valida também curso, turma e as 4 perguntas."""
        if not isinstance(data, dict):
            return None, "O corpo deve ser um objeto JSON."
        if not partial and any(k not in data for k in ("nome", "idade")):
            return None, "Informe nome e idade."

        cleaned = {}
        for field, limit in (("nome", 120), ("aspiracao", 300), ("universidade", 200)):
            if field in data:
                value = data[field]
                if value is None:
                    value = ""
                if not isinstance(value, str):
                    return None, f"{field} deve ser texto."
                value = value.strip()
                if field == "nome" and not value:
                    return None, "nome é obrigatório."
                if len(value) > limit:
                    return None, f"{field} deve ter no máximo {limit} caracteres."
                if field in ("nome", "universidade"):
                    cleaned[field] = value.title()
                else:
                    cleaned[field] = value.capitalize()

        if "idade" in data:
            age = data["idade"]
            if isinstance(age, bool) or not (isinstance(age, int) or (isinstance(age, str) and age.isdigit())):
                return None, "idade deve ser um número inteiro."
            age = int(age)
            if age < 1 or age > 120:
                return None, "idade deve estar entre 1 e 120."
            cleaned["idade"] = age
        elif not partial:
            return None, "idade é obrigatório."

        if survey:
            for field, choices in (("curso", CURSOS), ("turma", TURMAS)):
                value = data.get(field, "")
                if not isinstance(value, str):
                    return None, f"{field} deve ser texto."
                value = value.strip()
                if not value:
                    return None, "O curso é obrigatório." if field == "curso" else "A turma é obrigatória."
                if value not in choices:
                    return None, "Selecione um curso válido." if field == "curso" else "Selecione uma turma válida."
                cleaned[field] = value
            # (pergunta, resposta que abre o "por quê?", campo do motivo)
            for campo, (gatilho, campo_motivo) in {
                "interesse_area_tecnica": ("Não", "motivo_desinteresse"),
                "continuar_estudos": ("Não", "motivo_continuar_estudos"),
                "violencia_curso": ("Sim", "motivo_violencia_curso"),
                "violencia_futura": ("Sim", "motivo_violencia_futura"),
            }.items():
                resposta = data.get(campo, "")
                if not isinstance(resposta, str):
                    return None, "Responda Sim ou Não em todas as perguntas da etapa 2."
                resposta = resposta.strip()
                if not resposta and campo in PERGUNTAS_VIOLENCIA_OPCIONAIS:
                    cleaned[campo] = ""
                    cleaned[campo_motivo] = ""
                    continue
                if resposta not in ("Sim", "Não"):
                    return None, "Responda Sim ou Não em todas as perguntas da etapa 2."
                cleaned[campo] = resposta
                motivo = data.get(campo_motivo, "")
                if not isinstance(motivo, str):
                    return None, "Os campos de motivo devem ser texto."
                motivo = motivo.strip()
                if resposta == gatilho:
                    if len(motivo) > 300:
                        return None, "O 'por quê?' deve ter no máximo 300 caracteres."
                    if not motivo and campo_motivo not in MOTIVOS_VIOLENCIA_OPCIONAIS:
                        return None, "Conte um pouco mais no campo 'Por quê?' da resposta que você escolheu."
                    cleaned[campo_motivo] = motivo
                else:
                    cleaned[campo_motivo] = ""
        return cleaned, None

    def insert_student(data):
        perfil = {campo: data.get(campo, "") for campo in ("nome", "idade", "aspiracao", "universidade")}
        pesquisa = {campo: data.get(campo, "") for campo in SURVEY_COLUMNS}
        cols = [*perfil, *pesquisa]
        params = {**perfil, **pesquisa}
        with engine.begin() as conn:
            return conn.execute(
                text(f"INSERT INTO alunos ({', '.join(cols)}) VALUES ({', '.join(':' + c for c in cols)}) RETURNING id"),
                params,
            ).scalar_one()

    @app.get("/")
    def home():
        student = get_student(session.get("aluno_id"))
        if not student:
            session.pop("aluno_id", None)
        return render_template("index.html", aluno=student,
                               nome_usuario=student["nome"] if student else None,
                               abrir_perfil=False, cadastro_dados={}, cadastro_etapa=1)

    @app.post("/cadastrar")
    def cadastrar():
        data, error = validate_data(request.form.to_dict(), survey=True)
        if error:
            form_data = request.form.to_dict()
            campos_etapa_2 = {
                "interesse_area_tecnica", "continuar_estudos", "violencia_curso", "violencia_futura",
            }
            return render_template("index.html", aluno=None, nome_usuario=None,
                                   abrir_perfil=False, erro_cadastro=error,
                                   cadastro_dados=form_data,
                                   cadastro_etapa=2 if campos_etapa_2.intersection(form_data) else 1), 400
        session["aluno_id"] = insert_student(data)
        return redirect(url_for("home"))

    @app.get("/perfil")
    def perfil():
        student = get_student(session.get("aluno_id"))
        if not student:
            session.pop("aluno_id", None)
            return redirect(url_for("home"))
        return render_template("index.html", aluno=student, nome_usuario=student["nome"],
                               abrir_perfil=True, cadastro_dados={}, cadastro_etapa=1)

    @app.post("/perfil/atualizar")
    def atualizar_perfil():
        student_id = session.get("aluno_id")
        if not student_id:
            return redirect(url_for("home"))
        data, error = validate_data(request.form.to_dict())
        if error:
            student = get_student(student_id)
            return render_template("index.html", aluno=student,
                                   nome_usuario=student["nome"] if student else None,
                                   abrir_perfil=True,
                                   cadastro_dados={}, cadastro_etapa=1,
                                   erro_perfil="Preencha nome e idade para salvar."), 400
        data.setdefault("universidade", "")
        data.setdefault("aspiracao", "")
        with engine.begin() as conn:
            conn.execute(
                text("UPDATE alunos SET nome=:nome, idade=:idade, universidade=:universidade, "
                     "aspiracao=:aspiracao WHERE id=:id"),
                {**data, "id": student_id},
            )
        return redirect(url_for("perfil", atualizado="1"))

    # ---------- Chat global (inalterado) ----------
    @app.get("/api/chat")
    def api_chat_list():
        with engine.connect() as conn:
            rows = conn.execute(text("""
                SELECT mensagens.id, mensagens.aluno_id, alunos.nome, mensagens.mensagem, mensagens.criado_em
                FROM mensagens INNER JOIN alunos ON alunos.id = mensagens.aluno_id
                ORDER BY mensagens.id ASC""")).mappings().all()
        return jsonify(mensagens=[dict(r) for r in rows])

    @app.post("/api/chat")
    def api_chat_create():
        aluno_id = session.get("aluno_id")
        if not aluno_id:
            return jsonify(error="Você precisa estar cadastrado para participar do chat."), 401
        student = get_student(aluno_id)
        if not student:
            session.pop("aluno_id", None)
            return jsonify(error="Perfil não encontrado."), 401
        data = request.get_json(silent=True)
        if not isinstance(data, dict):
            return jsonify(error="O corpo deve ser um objeto JSON."), 400
        mensagem = data.get("mensagem")
        if not isinstance(mensagem, str):
            return jsonify(error="mensagem deve ser texto."), 400
        mensagem = mensagem.strip()
        if not mensagem:
            return jsonify(error="A mensagem não pode estar vazia."), 400
        if len(mensagem) > 1000:
            return jsonify(error="A mensagem deve ter no máximo 1000 caracteres."), 400
        with engine.begin() as conn:
            row = conn.execute(
                text("INSERT INTO mensagens (aluno_id, mensagem) VALUES (:aluno_id, :mensagem) RETURNING id, criado_em"),
                {"aluno_id": aluno_id, "mensagem": mensagem}).mappings().one()
        return jsonify(mensagem={"id": row["id"], "aluno_id": aluno_id, "nome": student["nome"],
                                 "mensagem": mensagem, "criado_em": row["criado_em"]}), 201

    return app


app = create_app()

if __name__ == "__main__":
    app.run(debug=os.environ.get("FLASK_DEBUG", "false").lower() == "true")
