"""WoHelp web app and JSON API."""
import os

from flask import Flask, jsonify, redirect, render_template, request, session, url_for
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DATABASE_URL = "sqlite:///" + os.path.join(BASE_DIR, "wohelp.db")


def database_url():
    url = os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL)

    if url.startswith("postgres://"):
        url = "postgresql+psycopg://" + url[len("postgres://"):]
    elif url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)

    return url


def create_app(test_config=None):
    app = Flask(__name__)

    app.config.update(
        SECRET_KEY=os.environ.get("WOHELP_SECRET_KEY", "dev-only-change-me"),
        SESSION_COOKIE_HTTPONLY=True,
        SESSION_COOKIE_SAMESITE=os.environ.get("SESSION_COOKIE_SAMESITE", "Lax"),
        SESSION_COOKIE_SECURE=os.environ.get("SESSION_COOKIE_SECURE", "false").lower() == "true",
        MAX_CONTENT_LENGTH=16 * 1024,
    )

    if test_config:
        app.config.update(test_config)

    engine = create_engine(
        app.config.get("DATABASE_URL") or database_url(),
        pool_pre_ping=True,
    )

    app.extensions["wohelp_engine"] = engine

    origins = {
        origin.strip().rstrip("/")
        for origin in os.environ.get("CORS_ORIGINS", "").split(",")
        if origin.strip()
    }

    def initialize_database():
        id_column = (
            "INTEGER PRIMARY KEY AUTOINCREMENT"
            if engine.dialect.name == "sqlite"
            else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        )

        with engine.begin() as conn:

            # Tabela dos usuários
            conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS alunos (
                    id {id_column},
                    nome TEXT NOT NULL,
                    idade INTEGER NOT NULL,
                    aspiracao TEXT,
                    universidade TEXT
                )
            """))

            # Tabela do chat global
            conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS mensagens (
                    id {id_column},
                    aluno_id INTEGER NOT NULL,
                    mensagem TEXT NOT NULL,
                    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (aluno_id) REFERENCES alunos(id)
                )
            """))

    with app.app_context():
        initialize_database()

    @app.after_request
    def cors_headers(response):
        origin = request.headers.get("Origin", "").rstrip("/")

        if origin in origins:
            response.headers["Access-Control-Allow-Origin"] = origin
            response.headers["Access-Control-Allow-Credentials"] = "true"
            response.headers["Access-Control-Allow-Headers"] = "Content-Type"
            response.headers["Access-Control-Allow-Methods"] = "GET, POST, PATCH, OPTIONS"
            response.headers["Vary"] = "Origin"

        return response

    @app.get("/health")
    def health():
        try:
            with engine.connect() as conn:
                conn.execute(text("SELECT 1"))

            return jsonify(status="ok")

        except SQLAlchemyError:
            return jsonify(status="unavailable"), 503

    def get_student(student_id):
        if not student_id:
            return None

        with engine.connect() as conn:
            row = conn.execute(
                text("""
                    SELECT
                        id,
                        nome,
                        idade,
                        aspiracao,
                        universidade
                    FROM alunos
                    WHERE id = :id
                """),
                {"id": student_id},
            ).mappings().first()

        return dict(row) if row else None

    def validate_data(data, partial=False):
        if not isinstance(data, dict):
            return None, "O corpo deve ser um objeto JSON."

        required = ("nome", "idade", "aspiracao")

        if not partial and any(key not in data for key in required):
            return None, "Informe nome, idade e aspiração."

        cleaned = {}

        for field, limit in (
            ("nome", 120),
            ("aspiracao", 300),
            ("universidade", 200),
        ):
            if field in data:
                value = data[field]

                if value is None and field == "universidade":
                    value = ""

                if not isinstance(value, str):
                    return None, f"{field} deve ser texto."

                value = value.strip()

                if field != "universidade" and not value:
                    return None, f"{field} é obrigatório."

                if len(value) > limit:
                    return None, f"{field} deve ter no máximo {limit} caracteres."

                if field in ("nome", "universidade"):
                    cleaned[field] = value.title()
                else:
                    cleaned[field] = value.capitalize()

        if "idade" in data:
            age = data["idade"]

            if isinstance(age, bool) or not (
                isinstance(age, int)
                or (isinstance(age, str) and age.isdigit())
            ):
                return None, "idade deve ser um número inteiro."

            age = int(age)

            if age < 1 or age > 120:
                return None, "idade deve estar entre 1 e 120."

            cleaned["idade"] = age

        elif not partial:
            return None, "idade é obrigatório."

        return cleaned, None

    def insert_student(data):
        with engine.begin() as conn:
            return conn.execute(
                text("""
                    INSERT INTO alunos (
                        nome,
                        idade,
                        aspiracao,
                        universidade
                    )
                    VALUES (
                        :nome,
                        :idade,
                        :aspiracao,
                        :universidade
                    )
                    RETURNING id
                """),
                data,
            ).scalar_one()

    @app.get("/")
    def home():
        student = get_student(session.get("aluno_id"))

        if not student:
            session.pop("aluno_id", None)

        return render_template(
            "index.html",
            aluno=student,
            nome_usuario=student["nome"] if student else None,
            abrir_perfil=bool(student),
        )

    @app.post("/cadastrar")
    def cadastrar():
        raw = request.form.to_dict()

        data, error = validate_data(raw)

        if error:
            return render_template(
                "index.html",
                aluno=None,
                nome_usuario=None,
                abrir_perfil=False,
                erro_cadastro=error,
            ), 400

        data.setdefault("universidade", "")

        session["aluno_id"] = insert_student(data)

        return redirect(url_for("perfil"))

    @app.get("/perfil")
    def perfil():
        student = get_student(session.get("aluno_id"))

        if not student:
            session.pop("aluno_id", None)
            return redirect(url_for("home"))

        return render_template(
            "index.html",
            aluno=student,
            nome_usuario=student["nome"],
            abrir_perfil=True,
        )

    @app.post("/perfil/atualizar")
    def atualizar_perfil():
        student_id = session.get("aluno_id")

        if not student_id:
            return redirect(url_for("home"))

        data, error = validate_data(request.form.to_dict())

        if error:
            student = get_student(student_id)

            return render_template(
                "index.html",
                aluno=student,
                nome_usuario=student["nome"] if student else None,
                abrir_perfil=True,
                erro_perfil="Preencha nome, idade e aspiração para salvar.",
            ), 400

        data.setdefault("universidade", "")

        with engine.begin() as conn:
            conn.execute(
                text("""
                    UPDATE alunos
                    SET
                        nome = :nome,
                        idade = :idade,
                        universidade = :universidade,
                        aspiracao = :aspiracao
                    WHERE id = :id
                """),
                {
                    **data,
                    "id": student_id,
                },
            )

        return redirect(url_for("perfil", atualizado="1"))

    @app.route("/api/alunos", methods=["POST", "OPTIONS"])
    def api_create_student():
        if request.method == "OPTIONS":
            return "", 204

        data, error = validate_data(
            request.get_json(silent=True)
        )

        if error:
            return jsonify(error=error), 400

        data.setdefault("universidade", "")

        student_id = insert_student(data)

        session["aluno_id"] = student_id

        return jsonify(
            aluno=get_student(student_id)
        ), 201

    @app.route("/api/perfil", methods=["GET", "PATCH", "OPTIONS"])
    def api_profile():
        if request.method == "OPTIONS":
            return "", 204

        student_id = session.get("aluno_id")

        student = get_student(student_id)

        if not student:
            session.pop("aluno_id", None)

            return jsonify(
                error="Perfil não encontrado."
            ), 401

        if request.method == "GET":
            return jsonify(
                aluno=student
            )

        data, error = validate_data(
            request.get_json(silent=True)
        )

        if error:
            return jsonify(error=error), 400

        data.setdefault("universidade", "")

        with engine.begin() as conn:
            conn.execute(
                text("""
                    UPDATE alunos
                    SET
                        nome = :nome,
                        idade = :idade,
                        universidade = :universidade,
                        aspiracao = :aspiracao
                    WHERE id = :id
                """),
                {
                    **data,
                    "id": student_id,
                },
            )

        return jsonify(
            aluno=get_student(student_id)
        )

    # ============================================================
    # CHAT GLOBAL
    # ============================================================

    @app.get("/api/chat")
    def api_chat_list():
        """
        Retorna todas as mensagens do chat global.
        """

        with engine.connect() as conn:
            rows = conn.execute(
                text("""
                    SELECT
                        mensagens.id,
                        mensagens.aluno_id,
                        alunos.nome,
                        mensagens.mensagem,
                        mensagens.criado_em
                    FROM mensagens
                    INNER JOIN alunos
                        ON alunos.id = mensagens.aluno_id
                    ORDER BY mensagens.id ASC
                """)
            ).mappings().all()

        return jsonify(
            mensagens=[
                dict(row)
                for row in rows
            ]
        )

    @app.post("/api/chat")
    def api_chat_create():
        """
        Envia uma mensagem para o chat global.
        """

        aluno_id = session.get("aluno_id")

        # Só usuários cadastrados podem enviar mensagens.
        if not aluno_id:
            return jsonify(
                error="Você precisa estar cadastrado para participar do chat."
            ), 401

        student = get_student(aluno_id)

        if not student:
            session.pop("aluno_id", None)

            return jsonify(
                error="Perfil não encontrado."
            ), 401

        data = request.get_json(silent=True)

        if not isinstance(data, dict):
            return jsonify(
                error="O corpo deve ser um objeto JSON."
            ), 400

        mensagem = data.get("mensagem")

        if not isinstance(mensagem, str):
            return jsonify(
                error="mensagem deve ser texto."
            ), 400

        mensagem = mensagem.strip()

        if not mensagem:
            return jsonify(
                error="A mensagem não pode estar vazia."
            ), 400

        if len(mensagem) > 1000:
            return jsonify(
                error="A mensagem deve ter no máximo 1000 caracteres."
            ), 400

        with engine.begin() as conn:
            row = conn.execute(
                text("""
                    INSERT INTO mensagens (
                        aluno_id,
                        mensagem
                    )
                    VALUES (
                        :aluno_id,
                        :mensagem
                    )
                    RETURNING id, criado_em
                """),
                {
                    "aluno_id": aluno_id,
                    "mensagem": mensagem,
                },
            ).mappings().one()

        return jsonify(
            mensagem={
                "id": row["id"],
                "aluno_id": aluno_id,
                "nome": student["nome"],
                "mensagem": mensagem,
                "criado_em": row["criado_em"],
            }
        ), 201

    # ============================================================

    return app


app = create_app()


if __name__ == "__main__":
    app.run(
        debug=os.environ.get(
            "FLASK_DEBUG",
            "false"
        ).lower() == "true"
    )