"""Copy all alunos rows from the legacy SQLite file into DATABASE_URL.

This command never deletes or modifies the SQLite source. It refuses to copy
into a non-empty destination table to avoid accidental duplicates/overwrites.
"""
import os
import sqlite3

from sqlalchemy import create_engine, text

from app import database_url


source_path = os.environ.get("SQLITE_SOURCE", os.path.join(os.path.dirname(__file__), "wohelp.db"))
destination_url = database_url()
if destination_url.startswith("sqlite:"):
    raise SystemExit("DATABASE_URL precisa apontar para PostgreSQL para executar esta migração.")

source = sqlite3.connect(source_path)
source.row_factory = sqlite3.Row
rows = source.execute("SELECT id,nome,idade,aspiracao,universidade FROM alunos ORDER BY id").fetchall()
engine = create_engine(destination_url, pool_pre_ping=True)

with engine.begin() as conn:
    conn.execute(text("""CREATE TABLE IF NOT EXISTS alunos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL, idade INTEGER NOT NULL, aspiracao TEXT, universidade TEXT
    )"""))
    existing = conn.execute(text("SELECT COUNT(*) FROM alunos")).scalar_one()
    if existing:
        raise SystemExit(f"Destino já contém {existing} registros; nenhum dado foi alterado.")
    if rows:
        conn.execute(text("""INSERT INTO alunos (id,nome,idade,aspiracao,universidade)
            VALUES (:id,:nome,:idade,:aspiracao,:universidade)"""), [dict(row) for row in rows])
    conn.execute(text("SELECT setval(pg_get_serial_sequence('alunos','id'), COALESCE((SELECT MAX(id) FROM alunos), 1), EXISTS(SELECT 1 FROM alunos))"))

with engine.connect() as conn:
    copied = conn.execute(text("SELECT COUNT(*) FROM alunos")).scalar_one()
    copied_ids = conn.execute(text("SELECT id FROM alunos ORDER BY id")).scalars().all()
source_ids = [row["id"] for row in rows]
if copied != len(rows) or copied_ids != source_ids:
    raise SystemExit("Verificação falhou: contagens ou IDs diferem. O arquivo SQLite original foi preservado.")
print(f"Migração verificada: {copied} registros copiados. SQLite original preservado: {source_path}")
